# Dependencies
markdown:         redcarpet
redcarpet:
  extensions:     [strikethrough,smart,with_toc_data,tables]
highlighter:      pygments

# Permalinks
permalink:        /posts/:title/

# Setup
title:            Test
tagline:          'NA'
description:      ''
url:              http://sudhansusingh22.github.io
baseurl:          '/'
paginate:         5
excerpt_separator: '<br>'
gems:
- jekyll-mentions
- jemoji
- jekyll-redirect-from
- jekyll-sitemap
- jekyll-paginate

#Author
author:
  name:           'Sudhansu Singh'
  url:            https://twitter.com/sudhansusingh22

# Social Integration
social:
  twitter:        sudhansusingh22
  github:         sudhansusingh22
  stackexchange:  triple.s
  linkedin:       sudhansusingh22
  disqus:
  addthis_pubid:

# Custom vars
version:          1.0.0

#Github
github:
  repo:           https://github.com/sudhansusingh22/sudhansusingh22.github.io

portfolio:
