# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               Test
tagline:             'NA'
description:         'Github projects'
url:                 http://sudhansusingh22.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Sudhansu
  url:
  email:

# Custom vars
version:             1.0.0
