# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
#relative_permalinks: true

# Setup
title:               La
tagline:             'A Jekyll theme'
description:         'A description'
url:                 https://sudhansusingh22.github.io
baseurl:             ''
paginate:            5

gems: [jekyll-paginate]
paginate_path: "page:num"
# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Custom vars
version:             1.0.0
